/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '14. 10. 30 오전 4:44' with Gradle 2.0
 *
 * @author Administrator, @date 14. 10. 30 오전 4:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
